<?php

defined('BASEPATH') OR exit('No direct script access allowed');

//Generated By CITerm (https://github.com/mohabmes/CITerm)

class {NAME} extends CI_Controller {

	public function index()
	{
		$this->load->view('welcome_message');
	}
}
