<?php

defined('BASEPATH') OR exit('No direct script access allowed');

//Generated By CITerm (https://github.com/mohabmes/CITerm)

class {NAME} extends CI_Model{

  function __construct()
  {
    parent::__construct();
  }

}
