<?php

defined('BASEPATH') OR exit('No direct script access allowed');

//Generated By CITerm (https://github.com/mohabmes/CITerm)
?>

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<title>{NAME}</title>
	<style type="text/css">
	</style>

</head>
<body>

  <div id="container">
  	<h1>$name</h1>
  	<div id="body">
  		<p>The page you are looking at is being generated by CITerm.</p>
  	</div>
  </div>

</body>
</html>
